version: '3.8'

networks:
  eims-network:
    driver: bridge

volumes:
  eimsdb_data:  # Volume for PostgreSQL data
  node_modules:  # Volume for frontend node modules

services:
  eims-db:
    image: postgres:17.5
    container_name: eims-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - eimsdb_data:/var/lib/postgresql/data
    networks:
      - eims-network

  backend:
    build: ./backend
    container_name: eims_backend
    depends_on:
      - eims-db
    restart: always
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: eims-db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - eims-network

  frontend:
    build: ./frontend
    container_name: eims_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - eims-network

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: eims_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - eims-db
    networks:
      - eims-network
